[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
# font = "ttf-jetbrains-mono"
size = 13

[font.bold]
style = "JetBrains Mono"

[font.normal]
family = "JetBrains Mono"
# family = "Inconsolata"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[terminal.shell]
program = "/usr/bin/fish"

[window]
opacity = 0.88

[window.padding]
x = 24
y = 16

[general]
import = ["~/.config/alacritty/base16_default_dark.toml"]
